### ISSUE TITLE
[BUG]  Barely's super needs to damage dummies

### ISSUE THREAD

**Issue by leorautenburger** [Iddmeister/BadStars#14]
barely's super doesn't do damage to dummies

use his super on a dummy to reproduce this

his super should do damage to dummies

[evidence](https://imgur.com/a/1UZbstE)

**Comment by Iddmeister** [comment]
Should his super do damage to dummies? Is it necessary?
@sWordy07  what do u think?

**Comment by Nothing00100** [comment]
@Iddmeister i think it should. i also think barley's range is too much.

**Comment by Iddmeister** [comment]
Ye I could nerf Barelys range, but I'm not sure about his super doing damage
